# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  chisel = {
    pname = "chisel";
    version = "dce2fe894ab58311c616c7674059b9a4efb17e0a";
    src = fetchFromGitHub {
      owner = "chipsalliance";
      repo = "chisel";
      rev = "dce2fe894ab58311c616c7674059b9a4efb17e0a";
      fetchSubmodules = false;
      sha256 = "sha256-VSuNGkJumDyLEMY4ZknVf31RuVFFbtr7oBtThPP30Yk=";
    };
    date = "2024-05-16";
  };
  chisel-interface = {
    pname = "chisel-interface";
    version = "71b913ea0f17346bc057e2d7ff4639738209a000";
    src = fetchFromGitHub {
      owner = "chipsalliance";
      repo = "chisel-interface";
      rev = "71b913ea0f17346bc057e2d7ff4639738209a000";
      fetchSubmodules = false;
      sha256 = "sha256-hV9zKOl+4B6GD0PJIAuUulEg/JPab6VlnKVVXlWuMj0=";
    };
    date = "2024-05-18";
  };
}
