# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  chisel = {
    pname = "chisel";
    version = "dce2fe894ab58311c616c7674059b9a4efb17e0a";
    src = fetchFromGitHub {
      owner = "chipsalliance";
      repo = "chisel";
      rev = "dce2fe894ab58311c616c7674059b9a4efb17e0a";
      fetchSubmodules = false;
      sha256 = "sha256-VSuNGkJumDyLEMY4ZknVf31RuVFFbtr7oBtThPP30Yk=";
    };
    date = "2024-05-16";
  };
  chisel-interface = {
    pname = "chisel-interface";
    version = "0d97ca7872f69cfcfb9ae1d72059bd62be606322";
    src = fetchFromGitHub {
      owner = "chipsalliance";
      repo = "chisel-interface";
      rev = "0d97ca7872f69cfcfb9ae1d72059bd62be606322";
      fetchSubmodules = false;
      sha256 = "sha256-R0F6AsxoKyFE334bF567er+InzQQMp9bLTlal/SgVhs=";
    };
    date = "2024-05-22";
  };
}
