# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  chisel = {
    pname = "chisel";
    version = "6c708b19f8407f531c47f9b4d37a2db5327fe677";
    src = fetchFromGitHub {
      owner = "chipsalliance";
      repo = "chisel";
      rev = "6c708b19f8407f531c47f9b4d37a2db5327fe677";
      fetchSubmodules = false;
      sha256 = "sha256-IMUTc5mzHMkce5omsNkqvPORZW20gjqe8iz6ETKRGd8=";
    };
    date = "2024-06-12";
  };
  chisel-interface = {
    pname = "chisel-interface";
    version = "0d97ca7872f69cfcfb9ae1d72059bd62be606322";
    src = fetchFromGitHub {
      owner = "chipsalliance";
      repo = "chisel-interface";
      rev = "0d97ca7872f69cfcfb9ae1d72059bd62be606322";
      fetchSubmodules = false;
      sha256 = "sha256-R0F6AsxoKyFE334bF567er+InzQQMp9bLTlal/SgVhs=";
    };
    date = "2024-05-22";
  };
}
