version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3"
    nodejs: "20"
  commands:
  # Commands from https://docs.antora.org/antora/latest/install-and-run-quickstart/
  - npm install antora asciidoctor-kroki @antora/lunr-extension
  - sed -i 's/REPLACE_ME/$LANG/g' base.yml
  - npx -y antora --fetch --to-dir $READTHEDOCS_OUTPUT/html base.yml
