site:
  title: OSCC-IP SDRAM Controller
  start_page: main::index.adoc
content:
  sources:
  - url: .
    start_paths:
    - zh-CN
    branches: HEAD
antora:
  extensions:
  - require: '@antora/lunr-extension'
ui:
  bundle:
    url: antora/ui-bundle.zip
    snapshot: true
  supplemental_files: antora/supplemental_ui
asciidoc:
  extensions:
  - asciidoctor-kroki
  attributes:
    kroki-fetch-diagram: true
    idprefix: ''
    idseparator: '-'
