# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  chisel = {
    pname = "chisel";
    version = "f347914dee389cebbe48ac4ef2e350e5ac1d267a";
    src = fetchFromGitHub {
      owner = "chipsalliance";
      repo = "chisel";
      rev = "f347914dee389cebbe48ac4ef2e350e5ac1d267a";
      fetchSubmodules = false;
      sha256 = "sha256-4sdVOhXt2Y4pmzLpImi+jvpi2exJ5f0vuN+iLnueESk=";
    };
  };
  chisel-interface = {
    pname = "chisel-interface";
    version = "bc958139345d327e7dc98c8f9f689b914a8fa2fb";
    src = fetchFromGitHub {
      owner = "chipsalliance";
      repo = "chisel-interface";
      rev = "bc958139345d327e7dc98c8f9f689b914a8fa2fb";
      fetchSubmodules = false;
      sha256 = "sha256-TH7ZzZwglaZ98roLZqdAKTV3emIgWo5/tR9xIJA51BU=";
    };
    date = "2024-09-02";
  };
}
