# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  chisel = {
    pname = "chisel";
    version = "f347914dee389cebbe48ac4ef2e350e5ac1d267a";
    src = fetchFromGitHub {
      owner = "chipsalliance";
      repo = "chisel";
      rev = "f347914dee389cebbe48ac4ef2e350e5ac1d267a";
      fetchSubmodules = false;
      sha256 = "sha256-4sdVOhXt2Y4pmzLpImi+jvpi2exJ5f0vuN+iLnueESk=";
    };
  };
  chisel-interface = {
    pname = "chisel-interface";
    version = "0d97ca7872f69cfcfb9ae1d72059bd62be606322";
    src = fetchFromGitHub {
      owner = "chipsalliance";
      repo = "chisel-interface";
      rev = "0d97ca7872f69cfcfb9ae1d72059bd62be606322";
      fetchSubmodules = false;
      sha256 = "sha256-R0F6AsxoKyFE334bF567er+InzQQMp9bLTlal/SgVhs=";
    };
    date = "2024-05-22";
  };
}
